package com.kairosapp.githubkotlinrepositories

const val REPOSITORY_NAME = "REPOSITORY_NAME"
const val REPOSITORY_OWNER = "REPOSITORY_OWNER"
const val REPOSITORY_DESCRIPTION = "REPOSITORY_DESCRIPTION"
const val REPOSITORY_WATCHERS_COUNT = "REPOSITORY_WATCHERS_COUNT"
const val REPOSITORY_STARS_COUNT = "REPOSITORY_STARS_COUNT"
const val REPOSITORY_FORKS_COUNT = "REPOSITORY_FOLLOWERS_COUNT"